apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-artifact
spec:
  type: {{ .Values.service.type }}
  selector:
    app: artifact
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8443
