{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (printf "%s-artifact" .Release.Name) }}
  labels:
    app: artifact
  {{- $annotations := .Values.serviceAccount.annotations }}
  {{- if .Values.storageKeyFallback.enabled }}
  {{- $annotations = omit $annotations "iam.gke.io/gcp-service-account" }}
  {{- end }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
